### ISSUE TITLE
Prettify: control panel, labels, etc.

### ISSUE THREAD

**Issue by sidneymbell** [czbiohub/howmanymolecules#8]

**Comment by sidneymbell** [comment]
Also: adjust the "global" coordinates to move the main svg left + up

**Comment by batson** [comment]
Trim features:

Sample accumulation (set default to accumulate)

Fix total molecules to 100. "every cell truly has 100 transcripts; set the number of molecules _sampled_" (total molecules per cell + sampling depth get combined).
